version: '3.7'

services:
  springboot-blog-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-blog-rest-api:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/blogdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=my-secret-pw
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=blogdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
